# Generated by Django 3.2.15 on 2023-02-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230209_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientamount',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
