# Generated by Django 3.2.15 on 2023-02-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(help_text='Обязательно для заполнения', max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Обязательно для заполнения. Максимум 150 букв.', max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
